[package]
name = "polorust"
version = "0.0.1"
authors = ["Frank Yao <frank.yao@cyanide.io>"]

[dependencies]
log = { version = "^0.4.1", features = ["max_level_debug"] } 
simplelog = "^0.5.0"
redux = { git = "https://github.com/knarfytrebil/redux-rs.git", branch = "master" }
json = "*"
termion = "*"

[dependencies.ws]
version = "*"
features = ["ssl"]

[dependencies.tui]
version = "0.2.1"
default-features = true 
features = ['termion']
