[package]
name = "polorust"
version = "0.1.0"
authors = ["Frank Yao <frank.yao@cyanide.io>"]

[dependencies]
log = "*"
json = "*"
termion = "*"
stderrlog = "*"
env_logger = "*"
redux = "0.1.0"

[dependencies.ws]
version = "*"
features = ["ssl"]

[dependencies.tui]
version = "0.2.1"
default-features = true 
features = ['termion']
