[package]
name = "polorust"
version = "0.0.1"
authors = ["Frank Yao <frank.yao@cyanide.io>"]

[dependencies]
redux = { git = "https://github.com/knarfytrebil/redux-rs.git", branch = "dev" }
log = { version = "^0.4.1", features = ["max_level_debug"] }
uuid = { version = "0.6", features = ["v4"] }
simplelog = "^0.5.0"
json = "*"
termion = "*"
regex="1"

[dependencies.ws]
version = "*"
features = ["ssl"]

[dependencies.tui]
version = "^0.6.0"

[dependencies.cpython]
version = "0.2.0"
default-features = false
features = ["python27-sys"]
# Uncomment the line below when python37 support is available
# features = ["python3-sys"]
