[package]
name = "polorust"
version = "0.0.1"
authors = ["Frank Yao <frank.yao@cyanide.io>"]

[dependencies]
log = "*"
json = "*"
termion = "*"
stderrlog = "*"
env_logger = "*"
redux = { git = "https://github.com/knarfytrebil/redux-rs.git", branch = "master" }

[dependencies.ws]
version = "*"
features = ["ssl"]

[dependencies.tui]
version = "0.2.1"
default-features = true 
features = ['termion']
